# Configuración para redirigir tráfico HTTP (Puerto 80) a HTTPS (Puerto 443)
server {
    listen 80;
    server_name _; # Escucha en cualquier dominio o IP

    # Redirección 301 (Permanente) hacia HTTPS
    return 301 https://$host$request_uri;
}

# Configuración del servidor HTTPS (Puerto 443)
server {
    listen 443 ssl;
    server_name _;

    # Rutas donde Nginx buscará los certificados SSL.
    ssl_certificate /etc/nginx/ssl/cert.pem;
    ssl_certificate_key /etc/nginx/ssl/key.pem;

    # Opciones de seguridad recomendadas para SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    # Directorio donde se encuentran los archivos construidos del PWA
    root /usr/share/nginx/html;
    index index.html;

    # Bloque principal para servir la aplicación
    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|json)$ {
        expires 1y;
        add_header Cache-Control "public, no-transform";
    }
}